title: "Codeurmystique's Portfolio"
description: "Bookmark this to keep an eye on my project updates! Remember ~ Data is the oil, Insight is the fire"

# URL setup for GitHub Pages
url: "https://codeurmystique.github.io"
baseurl: "" # keep empty for user.github.io repos

# Theme
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dirt"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

# Author
author:
  name: "Ogechi Laura Amajuoyi"
  bio: "Data Whisperer • Analytics Enthusiast"
  avatar: "/avatar.png" # (put avatar.png in root next to style.css)

# Navigation
navigation:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects/
  - title: "Process"
    url: /process/
  - title: "Visuals"
    url: /visuals/
  - title: "About"
    url: /about/

# Footer links
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/codeurmystique"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ogechiamajuoyi"
