title: "Codeurmystique's Portfolio"
description: "Bookmark this to keep an eye on my project updates! Remember ~ Data is the oil, Insight is the fire"

# The URL and Baseurl are configured correctly for a user/organization page.
url: "https://codeurmystique.github.io" 
baseurl: "" # Keep empty for user.github.io repo

# The recommended way to use a theme on GitHub Pages is with remote_theme.
# This fixes the "theme not found" error.
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dirt"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

# Your custom styles
sass:
  sass_dir: _sass
  style: compressed

# Navigation
navigation:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects/
  - title: "Process"
    url: /process/
  - title: "Visuals"
    url: /visuals/
  - title: "About"
    url: /about/

# Author
author:
  name: "Ogechi Laura Amajuoyi"
  bio: "Data Whisperer • Analytics Enthusiast"
  avatar: "/assets/images/avatar.png"

# Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github" # Font Awesome icon class for GitHub
      url: "https://github.com/codeurmystique" # Add the full URL to your GitHub profile
    # Consider adding your LinkedIn profile for a professional touch.
    # - label: "LinkedIn"
    #   icon: "fab fa-fw fa-linkedin"
    #   url: "https://www.linkedin.com/in/ogechiamajuoyi"
